import { createClient } from "https://esm.sh/@supabase/supabase-js@2"
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};const j=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,admin=createClient(url,service),n=(v:any)=>Math.max(0,Number(v||0));
async function auth(req:Request){const h=req.headers.get("Authorization")||"",token=h.replace(/^Bearer\s+/i,"");const c=createClient(url,anon,{global:{headers:{Authorization:h}}}),{data,error}=await c.auth.getUser(token);if(error||!data.user)throw new Error("Unauthorized");return data.user}
async function accessFor(user:any,eventId=""){let {data:a}=await admin.from("event_staff_access").select("*").eq("staff_user_id",user.id).eq("active",true);if(!a?.length&&user.email){const {data:m}=await admin.from("event_staff_access").select("*").ilike("email",user.email).eq("active",true);a=m||[];if(a.length)await admin.from("event_staff_access").update({staff_user_id:user.id,updated_at:new Date().toISOString()}).in("id",a.map((x:any)=>x.id))}const list=a||[];if(eventId){const r=list.find((x:any)=>String(x.event_id)===String(eventId));if(!r)throw new Error("You are not assigned to this event.");return r}return list}
async function load(owner:string,key:string,f:any){const {data,error}=await admin.from("app_storage").select("storage_value").eq("user_id",owner).eq("storage_key",key).maybeSingle();if(error)throw error;return data?.storage_value??f}async function save(owner:string,key:string,val:any){const {error}=await admin.from("app_storage").upsert({user_id:owner,storage_key:key,storage_value:val,updated_at:new Date().toISOString()},{onConflict:"user_id,storage_key"});if(error)throw error}
async function audit(owner:string,eventId:string,user:any,action:string,details:any={}){await admin.from("staff_action_log").insert({owner_user_id:owner,event_id:eventId,staff_user_id:user.id,staff_email:user.email||"",action,details})}
function ensureOpen(e:any){const s=String(e.status||"").trim().toLowerCase();if(["completed","closed","cancelled","canceled","archived"].includes(s))throw new Error("This event is closed. Staff operational access is no longer available.")}
async function shiftFor(userId:string,eventId:string){const {data}=await admin.from("staff_shifts").select("*").eq("staff_user_id",userId).eq("event_id",eventId).order("clock_in",{ascending:false}).limit(1).maybeSingle();return data||null}async function salesFor(userId:string,eventId:string){const {data}=await admin.from("stripe_orders").select("amount_total,status,created_at").eq("staff_user_id",userId).eq("event_id",eventId);const paid=(data||[]).filter((x:any)=>x.status==="paid");return{count:paid.length,total:paid.reduce((s:number,x:any)=>s+n(x.amount_total),0)}}
function perms(a:any){return{can_check_in:!!a.can_check_in,can_scan_qr:!!a.can_scan_qr,can_accept_payments:!!a.can_accept_payments,can_event_sales:!!a.can_event_sales,can_view_guest_list:!!a.can_view_guest_list,can_redeem_items:!!a.can_redeem_items}}
function eventbriteUrl(value:any){try{const u=new URL(String(value||""));return u.protocol==="https:"&&(u.hostname==="eventbrite.com"||u.hostname.endsWith(".eventbrite.com"))?u.href:""}catch{return""}}
function pooledCapacity(e:any,pool:string,fallback=0){const rows=(e.ticketTypes||[]).filter((t:any)=>t.active!==false&&String(t.sharedCapacityPool||"")===pool);return rows.reduce((max:number,t:any)=>Math.max(max,n(t.quantity)*Math.max(1,n(t.seatMultiplier)||1)),n(fallback))}
async function safeEvent(e:any,a:any,user:any,settings:any={},eventbrite:any={},venues:any=[]){
  const p=perms(a),shift=await shiftFor(user.id,String(e.id)),sales=await salesFor(user.id,String(e.id));
  const eventLink=eventbrite?.events?.[String(e.id)]||{},channels=settings?.ticketSalesChannels||{},venue=(venues||[]).find((v:any)=>String(v.id)===String(e.venueId));
  const paintCapacity=n(e.sharedPaintCapacity||e.capacityPools?.["paint-instruction"]||pooledCapacity(e,"paint-instruction"));
  const exhibitCapacity=n(e.sharedArtExhibitCapacity||e.capacityPools?.["art-exhibit"]||pooledCapacity(e,"art-exhibit"));
  const menu=(e.menuFinalized&&Array.isArray(e.finalizedMenuItems)?e.finalizedMenuItems:(e.menuItems||[]))
    .filter((x:any)=>x.active!==false&&n(x.price)>0)
    .map((x:any)=>({id:x.id,name:x.name||"Item",description:x.description||"",category:x.category||"",price:n(x.price),groupSize:Math.max(1,n(x.groupSize)||1),inventoryId:x.inventoryId||"",eventbriteTicketClassId:x.eventbriteTicketClassId||""}));
  return{
    id:e.id,name:e.name||"Event",date:e.date||"",time:e.time||"",status:e.status||"",venueName:e.venueName||e.venue||venue?.name||"",
    capacity:n(e.capacity),ticketsSold:n(e.ticketsSold),paintCapacity,paintTicketsSold:n(e.eventbritePaintTicketsSold),exhibitCapacity,exhibitTicketsSold:n(e.eventbriteExhibitTicketsSold),
    permissions:p,salesChannels:{eventbrite:channels.eventbrite!==false,stripe:channels.stripe===true,manual:channels.manual===true},eventbriteCheckoutUrl:eventbriteUrl(eventLink.publicUrl||e.eventbriteCheckoutUrl||e.eventbritePublicUrl),
    ticketTypes:(e.ticketTypes||[]).filter((t:any)=>t.active!==false).map((t:any)=>({id:t.id,name:t.name||"Ticket",description:t.description||"",price:n(t.price),kind:t.kind||"",groupSize:Math.max(1,n(t.groupSize)||1),regularValue:n(t.regularValue),eventbriteTicketClassId:t.eventbriteTicketClassId||""})),
    menuItems:p.can_event_sales?menu:[],
    guestList:p.can_view_guest_list?(e.guestList||[]).map((g:any)=>({id:g.id,name:g.name||g.customerName||[g.firstName,g.lastName].filter(Boolean).join(" "),email:g.email||g.customerEmail||"",status:g.status||"",checkedIn:!!g.checkedIn,ticketQuantity:n(g.ticketQuantity),source:g.source||""})):[],
    shift:shift?{id:shift.id,clockIn:shift.clock_in,clockOut:shift.clock_out,active:!shift.clock_out}:null,staffSales:sales
  }
}
async function eventbriteAttendee(owner:string,eventId:string,barcode:string){const eb=await load(owner,"eventbrite",{}),link=eb?.events?.[eventId],ebId=String(link?.eventbriteEventId||"");if(!ebId)throw new Error("This event is not linked to Eventbrite.");const token=Deno.env.get("EVENTBRITE_PRIVATE_TOKEN");if(!token)throw new Error("Eventbrite is not configured.");let page=1;while(page<=100){const r=await fetch(`https://www.eventbriteapi.com/v3/events/${encodeURIComponent(ebId)}/attendees/?page=${page}`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d?.error_description||d?.error||"Eventbrite lookup failed.");for(const a of d.attendees||[]){const code=String(a.barcodes?.[0]?.barcode||"");if(code===barcode)return a}if(!d.pagination?.has_more_items)break;page++}return null}
function eventbriteItem(e:any,att:any){const classId=String(att.ticket_class_id||""),className=String(att.ticket_class_name||"").trim().toLowerCase();return[...(e.ticketTypes||[]),...(e.menuItems||[])].find((x:any)=>String(x.eventbriteTicketClassId||"")===classId||String(x.name||"").trim().toLowerCase()===className)||null}
function buildEventbriteEntitlements(e:any,att:any){
  const item=eventbriteItem(e,att);if(!item)return[];
  const source=Array.isArray(item.inclusions)&&item.inclusions.length?item.inclusions:[{id:`eventbrite-item-${item.id||att.ticket_class_id||"item"}`,label:item.name||att.ticket_class_name||"Prepaid Item",quantity:1,redeemable:true,scope:"ticket",menuCategory:item.category||""}];
  e.sharedEntitlementRedemptions=e.sharedEntitlementRedemptions&&typeof e.sharedEntitlementRedemptions==="object"?e.sharedEntitlementRedemptions:{};
  return source.filter((x:any)=>x.redeemable!==false).map((x:any)=>{const scope=String(x.scope||"ticket"),sourceInclusionId=String(x.id||""),sharedKey=scope==="order"?`eventbrite-order:${att.order_id||att.id}:${sourceInclusionId||x.label||"included-item"}`:"",shared=e.sharedEntitlementRedemptions[sharedKey];return{id:crypto.randomUUID(),sourceInclusionId,label:x.label||"Included Item",menuCategory:x.menuCategory||"",quantity:Math.max(1,n(x.quantity)),scope,sharedKey,redeemed:sharedKey?n(shared?.redeemed):0,redemptions:[]}})
}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const user=await auth(req);if(req.method==="GET"){const accesses:any[]=await accessFor(user),out=[],ownerCache=new Map<string,any>();for(const a of accesses){const owner=String(a.owner_user_id);if(!ownerCache.has(owner))ownerCache.set(owner,Promise.all([load(owner,"events",[]),load(owner,"settings",{}),load(owner,"eventbrite",{}),load(owner,"venues",[])]));const [events,settings,eventbrite,venues]=await ownerCache.get(owner),e=events.find((x:any)=>String(x.id)===String(a.event_id));if(e)out.push(await safeEvent(e,a,user,settings,eventbrite,venues))}return j({ok:true,staff:{id:user.id,email:user.email||""},events:out})}const b=await req.json(),action=String(b.action||""),eventId=String(b.eventId||""),a:any=await accessFor(user,eventId),owner=String(a.owner_user_id),events=await load(owner,"events",[]),e=events.find((x:any)=>String(x.id)===eventId);if(!e)throw new Error("Event not found.");ensureOpen(e);
if(action==="clock_in"){const last=await shiftFor(user.id,eventId);if(last&&!last.clock_out)throw new Error("You are already clocked in.");const {data,error}=await admin.from("staff_shifts").insert({owner_user_id:owner,event_id:eventId,staff_user_id:user.id,staff_email:user.email||""}).select("*").single();if(error)throw error;await audit(owner,eventId,user,"clock_in");return j({ok:true,message:"Clocked in.",shift:data})}
if(action==="clock_out"){const last=await shiftFor(user.id,eventId);if(!last||last.clock_out)throw new Error("You are not currently clocked in.");const now=new Date().toISOString(),{data,error}=await admin.from("staff_shifts").update({clock_out:now,updated_at:now}).eq("id",last.id).select("*").single();if(error)throw error;await audit(owner,eventId,user,"clock_out");return j({ok:true,message:"Clocked out.",shift:data})}
if(action==="checkin_snp_ticket"){if(!a.can_check_in||!a.can_scan_qr)throw new Error("Check-in permission is not enabled.");const value=String(b.qr||"").trim(),p=value.split(":");if(!value.startsWith("SNP-TICKET:")||String(p[1])!==eventId)throw new Error("Invalid ticket for this event.");const pass=(e.ticketPasses||[]).find((x:any)=>String(x.id)===String(p[2]||""));if(!pass)throw new Error("Ticket not found.");const blocked=["refunded","partially refunded","partially_refunded","cancelled","canceled","void","voided","inactive","revoked"].includes(String(pass.status||"").toLowerCase())||!!pass.refundedAt||pass.active===false;if(blocked)throw new Error("REFUNDED / INACTIVE TICKET: admission denied.");if(pass.checkedIn)throw new Error("DUPLICATE TICKET: this ticket is already checked in.");const now=new Date().toISOString();pass.checkedIn=true;pass.checkedInAt=now;pass.status="Checked In";e.checkIns=Array.isArray(e.checkIns)?e.checkIns:[];e.checkIns.push({ticketId:pass.id,checkedInAt:now,source:"Staff Portal",staffUserId:user.id,staffEmail:user.email||""});const g=(e.guestList||[]).find((x:any)=>String(x.id)===String(pass.guestId||""));if(g){const gp=(e.ticketPasses||[]).filter((x:any)=>String(x.guestId||"")===String(g.id)),c=gp.filter((x:any)=>x.checkedIn).length;g.checkedInCount=c;g.checkedIn=c>=gp.length&&gp.length>0;g.status=g.checkedIn?"Checked In":"Partially Checked In"}await save(owner,"events",events);await audit(owner,eventId,user,"checkin_snp_ticket",{ticketId:pass.id});return j({ok:true,message:"SNP ticket checked in."})}
if(action==="checkin_eventbrite"){if(!a.can_check_in||!a.can_scan_qr)throw new Error("Check-in permission is not enabled.");const code=String(b.qr||"").trim();if(!code)throw new Error("Scan or enter an Eventbrite barcode.");const att:any=await eventbriteAttendee(owner,eventId,code);if(!att)throw new Error("Eventbrite barcode not found for this event.");if(att.cancelled||att.refunded)throw new Error("REFUNDED / CANCELLED EVENTBRITE TICKET: admission denied.");e.eventbriteStaffCheckIns=Array.isArray(e.eventbriteStaffCheckIns)?e.eventbriteStaffCheckIns:[];if(e.eventbriteStaffCheckIns.some((x:any)=>String(x.attendeeId)===String(att.id)))throw new Error("DUPLICATE TICKET: this Eventbrite attendee was already checked in through SNP Planner.");const now=new Date().toISOString();e.eventbriteStaffCheckIns.push({attendeeId:String(att.id),barcode:code,name:String(att.profile?.name||""),email:String(att.profile?.email||""),ticketClassName:String(att.ticket_class_name||""),checkedInAt:now,staffUserId:user.id,staffEmail:user.email||""});await save(owner,"events",events);await audit(owner,eventId,user,"checkin_eventbrite",{attendeeId:String(att.id)});return j({ok:true,message:`Eventbrite ticket accepted for ${att.profile?.name||"guest"}.`,warning:att.checked_in?"Eventbrite already reports this attendee checked in.":"Recorded in SNP Planner. Eventbrite remains the source of truth for its own native check-in status."})}
if(action==="inspect_eventbrite_entitlements"){if(!a.can_redeem_items||!a.can_scan_qr)throw new Error("Redemption permission is not enabled.");const code=String(b.barcode||"").trim();if(!code)throw new Error("Scan or enter an Eventbrite barcode.");const att:any=await eventbriteAttendee(owner,eventId,code);if(!att)throw new Error("Eventbrite barcode not found for this event.");if(att.cancelled||att.refunded)throw new Error("REFUNDED / CANCELLED EVENTBRITE PURCHASE: redemption denied.");e.externalEntitlements=e.externalEntitlements&&typeof e.externalEntitlements==="object"?e.externalEntitlements:{};e.sharedEntitlementRedemptions=e.sharedEntitlementRedemptions&&typeof e.sharedEntitlementRedemptions==="object"?e.sharedEntitlementRedemptions:{};let rec=e.externalEntitlements[String(att.id)];if(!rec){rec={source:"Eventbrite",attendeeId:String(att.id),orderId:String(att.order_id||""),ticketClassName:String(att.ticket_class_name||""),entitlements:buildEventbriteEntitlements(e,att)};e.externalEntitlements[String(att.id)]=rec;await save(owner,"events",events)}for(const ent of rec.entitlements||[]){if(ent.sharedKey)ent.redeemed=n(e.sharedEntitlementRedemptions[ent.sharedKey]?.redeemed)}return j({ok:true,pass:{attendeeId:String(att.id),ticketClassName:String(att.ticket_class_name||"Eventbrite Purchase"),customerName:String(att.profile?.name||""),items:(rec.entitlements||[]).map((x:any)=>({id:x.id,label:x.label||"Item",quantity:Math.max(1,n(x.quantity)),redeemed:n(x.redeemed),remaining:Math.max(0,Math.max(1,n(x.quantity))-n(x.redeemed))}))}})}
if(action==="redeem_eventbrite_entitlement"){if(!a.can_redeem_items||!a.can_scan_qr)throw new Error("Redemption permission is not enabled.");e.externalEntitlements=e.externalEntitlements&&typeof e.externalEntitlements==="object"?e.externalEntitlements:{};e.sharedEntitlementRedemptions=e.sharedEntitlementRedemptions&&typeof e.sharedEntitlementRedemptions==="object"?e.sharedEntitlementRedemptions:{};const rec=e.externalEntitlements[String(b.attendeeId||"")];if(!rec)throw new Error("Scan the Eventbrite ticket and find its included items first.");const ent=(rec.entitlements||[]).find((x:any)=>String(x.id)===String(b.entitlementId||""));if(!ent)throw new Error("Included Eventbrite item not found.");if(ent.sharedKey)ent.redeemed=n(e.sharedEntitlementRedemptions[ent.sharedKey]?.redeemed);if(n(ent.redeemed)>=Math.max(1,n(ent.quantity)))throw new Error("This included item is already fully redeemed.");ent.redeemed=n(ent.redeemed)+1;ent.redemptions=Array.isArray(ent.redemptions)?ent.redemptions:[];ent.redemptions.push({redeemedAt:new Date().toISOString(),staffUserId:user.id,staffEmail:user.email||""});if(ent.sharedKey)e.sharedEntitlementRedemptions[ent.sharedKey]={redeemed:ent.redeemed,redemptions:ent.redemptions};await save(owner,"events",events);await audit(owner,eventId,user,"redeem_eventbrite_entitlement",{attendeeId:rec.attendeeId||"",entitlementId:ent.id,label:ent.label||"Item",sharedKey:ent.sharedKey||""});return j({ok:true,message:`${ent.label||"Item"} redeemed.`})}
if(action==="inspect_prepaid"){if(!a.can_redeem_items||!a.can_scan_qr)throw new Error("Redemption permission is not enabled.");const value=String(b.qr||"").trim(),p=value.split(":");if(!value.startsWith("SNP-PREPAID:")||String(p[1])!==eventId)throw new Error("Invalid prepaid QR for this event.");const pass=(e.prepaidPasses||[]).find((x:any)=>String(x.id)===String(p[2]||""));if(!pass)throw new Error("Prepaid order not found.");if(["refunded","partially_refunded","cancelled","voided","inactive","revoked"].includes(String(pass.status||"").toLowerCase())||pass.refundedAt||pass.active===false)throw new Error("REFUNDED / INACTIVE PURCHASE: redemption denied.");return j({ok:true,pass:{id:pass.id,status:pass.status||"Active",items:(pass.entitlements||[]).map((x:any)=>({id:x.id,label:x.label||"Item",quantity:n(x.quantity),redeemed:n(x.redeemed),remaining:Math.max(0,n(x.quantity)-n(x.redeemed))}))}})}
if(action==="redeem_prepaid"){if(!a.can_redeem_items||!a.can_scan_qr)throw new Error("Redemption permission is not enabled.");const pass=(e.prepaidPasses||[]).find((x:any)=>String(x.id)===String(b.passId||""));if(!pass)throw new Error("Prepaid order not found.");if(["refunded","partially_refunded","cancelled","voided","inactive","revoked"].includes(String(pass.status||"").toLowerCase())||pass.refundedAt||pass.active===false)throw new Error("REFUNDED / INACTIVE PURCHASE: redemption denied.");const ent=(pass.entitlements||[]).find((x:any)=>String(x.id)===String(b.entitlementId||""));if(!ent)throw new Error("Prepaid item not found.");if(n(ent.redeemed)>=n(ent.quantity))throw new Error("This item is already fully redeemed.");ent.redeemed=n(ent.redeemed)+1;ent.redemptions=Array.isArray(ent.redemptions)?ent.redemptions:[];ent.redemptions.push({redeemedAt:new Date().toISOString(),staffUserId:user.id,staffEmail:user.email||""});pass.status=(pass.entitlements||[]).every((x:any)=>n(x.redeemed)>=n(x.quantity))?"Redeemed":"Active";await save(owner,"events",events);await audit(owner,eventId,user,"redeem_prepaid",{passId:pass.id,entitlementId:ent.id,label:ent.label||"Item"});return j({ok:true,message:`${ent.label||"Item"} redeemed.`})}
return j({ok:false,error:"Unsupported staff action."},400)}catch(err){return j({ok:false,error:err instanceof Error?err.message:"Request failed."},err instanceof Error&&err.message==="Unauthorized"?401:400)}});
